### ISSUE TITLE
Paket.dependencies file cannot be processed.

### ISSUE THREAD

**Issue by nojaf** [snyk/snyk-paket-parser#40]
- `node -v`: 14.16.1
- `npm -v`: 6.14.12

### Expected behaviour

I'm trying to run `snyk test --file=paket.dependencies` and I expect my lock file to be parsed.

### Actual behaviour

```
Cannot read property 'refs' of undefined
```

Full log:
```
  snyk test <ref *1> {
  _: [ [Circular *1] ],
  file: 'paket.dependencies',
  debug: true
} +0ms
  snyk:run-test Error running test {
  error: TypeError: Cannot read property 'refs' of undefined
      at calculateReferences (C:\ProgramData\nvm\v14.16.1\node_modules\snyk\node_modules\snyk-paket-parser\lib\index.ts:177:5)
      at calculateReferences (C:\ProgramData\nvm\v14.16.1\node_modules\snyk\node_modules\snyk-paket-parser\lib\index.ts:181:7)
      at C:\ProgramData\nvm\v14.16.1\node_modules\snyk\node_modules\snyk-paket-parser\lib\index.ts:85:7
      at Generator.next (<anonymous>)
      at C:\ProgramData\nvm\v14.16.1\node_modules\snyk\node_modules\tslib\tslib.js:115:75
      at new Promise (<anonymous>)
      at Object.__awaiter (C:\ProgramData\nvm\v14.16.1\node_modules\snyk\node_modules\tslib\tslib.js:111:16)
      at buildDepTree (C:\ProgramData\nvm\v14.16.1\node_modules\snyk\node_modules\snyk-paket-parser\dist\index.js:42:20)
      at Object.<anonymous> (C:\ProgramData\nvm\v14.16.1\node_modules\snyk\node_modules\snyk-paket-parser\lib\index.ts:63:25)
      at Generator.next (<anonymous>)
      at C:\ProgramData\nvm\v14.16.1\node_modules\snyk\node_modules\tslib\tslib.js:115:75
      at new Promise (<anonymous>)
      at Object.__awaiter (C:\ProgramData\nvm\v14.16.1\node_modules\snyk\node_modules\tslib\tslib.js:111:16)
      at Object.buildDepTreeFromFiles (C:\ProgramData\nvm\v14.16.1\node_modules\snyk\node_modules\snyk-paket-parser\dist\index.js:20:20)
      at Object.inspect (C:\ProgramData\nvm\v14.16.1\node_modules\snyk\node_modules\snyk-nuget-plugin\lib\index.ts:55:8)
      at Object.inspect (C:\ProgramData\nvm\v14.16.1\node_modules\snyk\src\lib\module-info\index.ts:22:33)
      at Object.getSinglePluginResult (C:\ProgramData\nvm\v14.16.1\node_modules\snyk\src\lib\plugins\get-single-plugin-result.ts:13:64)
      at Object.getDepsFromPlugin (C:\ProgramData\nvm\v14.16.1\node_modules\snyk\src\lib\plugins\get-deps-from-plugin.ts:103:22)
      at assembleLocalPayloads (C:\ProgramData\nvm\v14.16.1\node_modules\snyk\src\lib\snyk-test\run-test.ts:570:24)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at runTest (C:\ProgramData\nvm\v14.16.1\node_modules\snyk\src\lib\snyk-test\run-test.ts:333:22)
      at test (C:\ProgramData\nvm\v14.16.1\node_modules\snyk\src\cli\commands\test\index.ts:93:15)
      at runCommand (C:\ProgramData\nvm\v14.16.1\node_modules\snyk\src\cli\index.ts:57:25)
      at main (C:\ProgramData\nvm\v14.16.1\node_modules\snyk\src\cli\index.ts:313:11)
} +0ms
  snyk-test Failed to test 1 projects, errors: +0ms
  snyk-test error: FailedToRunTestError: Cannot read property 'refs' of undefined
    at runTest (C:\ProgramData\nvm\v14.16.1\node_modules\snyk\src\lib\snyk-test\run-test.ts:364:11)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at test (C:\ProgramData\nvm\v14.16.1\node_modules\snyk\src\cli\commands\test\index.ts:93:15)
    at runCommand (C:\ProgramData\nvm\v14.16.1\node_modules\snyk\src\cli\index.ts:57:25)
    at main (C:\ProgramData\nvm\v14.16.1\node_modules\snyk\src\cli\index.ts:313:11) +1ms
Error:
Testing C:\MyRepoFolder...

Cannot read property 'refs' of undefined
    at test (C:\ProgramData\nvm\v14.16.1\node_modules\snyk\src\cli\commands\test\index.ts:241:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at runCommand (C:\ProgramData\nvm\v14.16.1\node_modules\snyk\src\cli\index.ts:57:25)
    at main (C:\ProgramData\nvm\v14.16.1\node_modules\snyk\src\cli\index.ts:313:11)

  snyk Exit code: 2 +0ms
  snyk analytics {
  "args": [
    {
      "file": "paket.dependencies",
      "debug": true
    }
  ],
  "command": "bad-command",
  "metadata": {
    "local": true,
    "error-message": "\nTesting C:\MyRepoFolder...\n\nCannot read property 'refs' of undefined",
    "error": "Error: \nTesting C:\MyRepoFolder...\n\nCannot read property 'refs' of undefined\n    at test (C:\\ProgramData\\nvm\\v14.16.1\\node_modules\\snyk\\src\\cli\\commands\\test\\index.ts:241:19)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5
)\n    at runCommand (C:\\ProgramData\\nvm\\v14.16.1\\node_modules\\snyk\\src\\cli\\index.ts:57:25)\n    at main (C:\\ProgramData\\nvm\\v14.16.1\\node_modules\\snyk\\src\\cli\\index.ts:313:11)",
    "error-code": 500,
    "command": "test"
  },
  "version": "1.667.0",
  "os": "Windows 10",
  "nodeVersion": "v14.16.1",
  "standalone": false,
  "integrationName": "",
  "integrationVersion": "",
  "integrationEnvironment": "",
  "integrationEnvironmentVersion": "",
  "id": "e963de0cf36540eafabf8f3f21dee94c57212d2b",
  "ci": false,
  "environment": {
    "npmVersion": "6.14.12"
  },
  "durationMs": 1146,
  "metrics": {
    "network_time": {
      "type": "timer",
      "values": [],
      "total": 0
    },
    "cpu_time": {
      "type": "synthetic",
      "values": [
        1146
      ],
      "total": 1146
    }
  }
} +0ms
  snyk sending request to: https://snyk.io/api/v1/analytics/cli +0ms
  snyk request body size: 1211 +0ms
  snyk gzipped request body size: 575 +0ms
  snyk not using proxy +1ms

```

### Steps to reproduce

I've attached my paket.dependencies and lock file.
[paket.dependencies.txt](https://github.com/snyk/snyk-paket-parser/files/6879495/paket.dependencies.txt)
[paket.lock.txt](https://github.com/snyk/snyk-paket-parser/files/6879496/paket.lock.txt)

---

If applicable, please append any error output here **ensuring to remove any sensitive/personal details or tokens.

**Comment by nojaf** [comment]
I was able to retrace this to `Fake.Runtime` being the bad apple.
